---
- name: Install Jenkins (working version)
  hosts: jenkins_servers
  become: yes

  tasks:

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Copy Jenkins package
      copy:
        src: jenkins_2.479.3_all.deb
        dest: /tmp/jenkins.deb

    - name: Install Jenkins
      apt:
        deb: /tmp/jenkins.deb

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
